In [1]:
import json

In [2]:
dados = []
with open('tweets_5min.json') as arquivo:
    for linha in arquivo:
        dados.append(json.loads(linha))

In [4]:
import pandas as pd
df = pd.DataFrame(dados)
df.head(2)

,contributors,coordinates,created_at,display_text_range,entities,extended_entities,extended_tweet,favorite_count,favorited,filter_level,...,quoted_status_id_str,reply_count,retweet_count,retweeted,retweeted_status,source,text,timestamp_ms,truncated,user
0,None,None,Mon Aug 01 21:16:54 +0000 2016,NaN,"{'hashtags': [{'text': 'MachineLearning', 'ind...",NaN,NaN,0,False,low,...,NaN,NaN,0,False,{'created_at': 'Mon Aug 01 18:15:16 +0000 2016...,"<a href=""http://twitter.com/download/android"" ...",RT @tonyojeda3: An Introduction to #MachineLea...,1470086214369,False,"{'id': 1432123832, 'id_str': '1432123832', 'na..."
1,None,None,Mon Aug 01 21:17:01 +0000 2016,NaN,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,NaN,0,False,low,...,NaN,NaN,0,False,NaN,"<a href=""http://publicize.wp.com/"" rel=""nofoll...",Course: 100% Off Big Data and Hadoop for https...,1470086221058,False,"{'id': 983245148, 'id_str': '983245148', 'name..."

In [8]:
import pandas as pd
df = pd.DataFrame(dados)
print(df.created_at.iloc[0])
#print(df.user.iloc[0])
print(df.user.iloc[0]['name'])

Mon Aug 01 21:16:54 +0000 2016
Ermia Bivatan

In [9]:
print(df['text'])

0     RT @tonyojeda3: An Introduction to #MachineLea...
1     Course: 100% Off Big Data and Hadoop for https...
2     Check out HackOn(Data) in Sept: bringing toget...
3     RT @wesmckinn: If you want to get more engaged...
4     Resposta: Iniciar uma ferramenta de linha de c...
5     RT @LauritaApplez: #Python devs looking for a ...
6     #nowplaying #ipad Python Bootcamp: Understandi...
7     @GaryEll85341441 @KissaSins @iamshylaj @JennaS...
8     That is one big solid state drive.\n\n15.56 TB...
9     @Steve__Zissou @Tsad https://t.co/QcpY9Fq0dT l...
10    #NowPlaying - Crocodile Python (Clean) - Rick ...
11    RT @SecurityTube: Free video on Finding All Wi...
12    We are open for (Big) Data thought leaders who...
13    RT @telefonicaid: #BigData #RRSS: nuevas herra...
14    @vambenepe interesting challenge on APIs thoug...
15    Job ad - SOFTWARE DEVELOPER (BIG DATA) https:/...
16    Job ad - SOFTWARE DEVELOPER (BIG DATA) https:/...
17    #jobs Big Data Engineer in Santa Clara,CA\nhtt...
18    Big data stirs visions of 'mobile machinery' h...
19    Big Data Analytic and Important Question https...
20    Anatomía de un experto en Big Data. #SocialMed...
21    @danfarina it's 2016 and you're forcing Python...
22    So proud of my ASU colleagues! "Through the lo...
23    RT @billsoftnet: Big Data Analysts vs Big Data...
24    RT @billsoftnet: Big Data Analysts vs Big Data...
25    #JobSearch : Senior Developer – Big Data https...
26    GI JOE COBRA VINTAGE 1989 PYTHON PATROL TELE-V...
27    RT @duckduckhack: Python coders using #Conda f...
28    #Python #statistics post on Reddit: [QUIZ] Whe...
29    RT @billsoftnet: Big Data Analysts vs Big Data...
                            ...
58    RT @Rbloggers: New R job: Big Data in Digital ...
59    Searching for amazing #FullStack #Developers f...
60    Hot Video! John Cleese and Eric Idle of 'Monty...
61    How do I calculate the date six months from th...
62    RT @billsoftnet: Big Data Analysts vs Big Data...
63    Senior Developer – Big Data #Hiring Migrate Da...
64    John Snow Labs Now Provides Curated Data in Ap...
65    @matthewherper @ethanjweiss lookout for PSA da...
66    RT @wesmckinn: If you want to get more engaged...
67    John Snow Labs Now Provides Curated Data in Ap...
68    @arntzenius with statements, if/for etc with t...
69    RT @adamsconsulting: Past, Present and Future ...
70    Utiliza #python con tu #Arduino: Python + Ardu...
71    RT @BLUTecnologia: ¿Qué es Big Data? ¿Qué es y...
72    RT @StatsBlogs: Working With R and Big Data: U...
73    Softkitect : Quantum Big Data Cloud AI Book Ch...
74    Softkitect : Quantum Big Data Cloud AI Book Ch...
75    Robert Mercer: the big data billionaire waging...
76    Working with #Couchbase from #Delphi - https:/...
77    @michaelwaskom You mean “Before python was coo...
78     誰一人として話題にしてないけどREPLがjava9で実装されたので\nPythonにも負けません
79    Man Found Dead In His Bedroom Beside His Pytho...
80    RT @AriMelber: New FBI annual crime data out:\...
81    RT @JimMarous: Potential of Fintechs, Big Data...
82    @untipsyteacher Used for Monty Python and the ...
83    RT @BonKu: Playgrounds as public health interv...
84    Hello Python! KittenBlock V1.4 support to use ...
85    Come and see us at poster S19 at the Big Data ...
86    @Emmanuelmarks2 @ogundamisi This python is not...
87    Satu kali prnh ngobrol ma tmn yg gila maen onl...
Name: text, Length: 88, dtype: object

In [25]:
print(df['text'].loc[0])
print(df['created_at'].loc[0])
print(df['coordinates'].loc[0])
print(df['retweet_count'].loc[0])

print(df['user'].loc[0]['screen_name'])
print(df['user'].loc[0]['created_at'])
print(df['user'].loc[0]['location'])
print(df['user'].loc[0]['lang'])
print(df['user'].loc[0]['followers_count'])

RT @tonyojeda3: An Introduction to #MachineLearning with #Python https://t.co/TMrLLJNskx #DataScience #BigData
Mon Aug 01 21:16:54 +0000 2016
None
0
ErmiaBivatan
Thu May 16 04:12:02 +0000 2013
None
en
135

In [19]:
colunas = ['text', 'created_at', 'coordinates','retweet_count', 'screen_name']

In [23]:
df_aux = pd.DataFrame(columns=colunas)
df_aux

Empty DataFrame
Columns: [text, created_at, coordinates, retweet_count, screen_name]
Index: []

In [26]:
df_aux.loc[0] = [
df['text'].loc[0],
df['created_at'].loc[0],
df['coordinates'].loc[0],
df['retweet_count'].loc[0],

df['user'].loc[0]['screen_name'],
#df['user'].loc[0]['created_at'],
#df['user'].loc[0]['location'],
#df['user'].loc[0]['lang'],
#df['user'].loc[0]['followers_count'],
    
]

In [27]:
df_aux

,text,created_at,coordinates,retweet_count,screen_name
0,RT @tonyojeda3: An Introduction to #MachineLea...,Mon Aug 01 21:16:54 +0000 2016,None,0,ErmiaBivatan

In [52]:
for i in range (0, len(df)):
    df_aux.loc[i] = [
        df['text'].loc[i],
        df['created_at'].loc[i],
        df['coordinates'].loc[i],
        df['retweet_count'].loc[i],

        df['user'].loc[i]['screen_name'],
        #df['user'].loc[0]['created_at'],
        #df['user'].loc[0]['location'],
        #df['user'].loc[0]['lang'],
        #df['user'].loc[0]['followers_count'],

]

In [30]:
df_aux

,text,created_at,coordinates,retweet_count,screen_name
0,RT @tonyojeda3: An Introduction to #MachineLea...,Mon Aug 01 21:16:54 +0000 2016,None,0,ErmiaBivatan
1,Course: 100% Off Big Data and Hadoop for https...,Mon Aug 01 21:17:01 +0000 2016,None,0,DkaliRam
2,Check out HackOn(Data) in Sept: bringing toget...,Mon Aug 01 21:17:03 +0000 2016,None,0,lightbend
3,RT @wesmckinn: If you want to get more engaged...,Mon Aug 01 21:17:13 +0000 2016,None,0,cool_python
4,Resposta: Iniciar uma ferramenta de linha de c...,Mon Aug 01 21:17:19 +0000 2016,None,0,drgarcia1986
5,RT @LauritaApplez: #Python devs looking for a ...,Mon Aug 01 21:17:25 +0000 2016,None,0,HoGueRa27
6,#nowplaying #ipad Python Bootcamp: Understandi...,Mon Aug 01 21:17:34 +0000 2016,None,0,NowPlaying_Here
7,@GaryEll85341441 @KissaSins @iamshylaj @JennaS...,Mon Aug 01 21:17:39 +0000 2016,None,0,HAWKWIND967
8,That is one big solid state drive.\n\n15.56 TB...,Mon Aug 01 21:17:42 +0000 2016,None,0,GTAmissions1
9,@Steve__Zissou @Tsad https://t.co/QcpY9Fq0dT l...,Mon Aug 01 21:17:42 +0000 2016,None,0,sizeof
10,#NowPlaying - Crocodile Python (Clean) - Rick ...,Mon Aug 01 21:17:45 +0000 2016,None,0,heat100radio
11,RT @SecurityTube: Free video on Finding All Wi...,Mon Aug 01 21:17:48 +0000 2016,None,0,HoGueRa27
12,We are open for (Big) Data thought leaders who...,Mon Aug 01 21:17:51 +0000 2016,None,0,Datafloq
13,RT @telefonicaid: #BigData #RRSS: nuevas herra...,Mon Aug 01 21:17:53 +0000 2016,None,0,BigDataCol
14,@vambenepe interesting challenge on APIs thoug...,Mon Aug 01 21:17:53 +0000 2016,None,0,mosesjones
15,Job ad - SOFTWARE DEVELOPER (BIG DATA) https:/...,Mon Aug 01 21:17:57 +0000 2016,None,0,TheHyipLife
16,Job ad - SOFTWARE DEVELOPER (BIG DATA) https:/...,Mon Aug 01 21:17:57 +0000 2016,None,0,webinvestnews
17,"#jobs Big Data Engineer in Santa Clara,CA\nhtt...",Mon Aug 01 21:18:00 +0000 2016,None,0,nPgigs
18,Big data stirs visions of 'mobile machinery' h...,Mon Aug 01 21:18:11 +0000 2016,None,0,SociativeBigDat
19,Big Data Analytic and Important Question https...,Mon Aug 01 21:18:11 +0000 2016,None,0,SociativeBigDat
20,Anatomía de un experto en Big Data. #SocialMed...,Mon Aug 01 21:18:11 +0000 2016,None,0,ShimmerTechno
21,@danfarina it's 2016 and you're forcing Python...,Mon Aug 01 21:18:29 +0000 2016,None,0,drnic
22,"So proud of my ASU colleagues! ""Through the lo...",Mon Aug 01 21:18:32 +0000 2016,None,0,gnkuyps
23,RT @billsoftnet: Big Data Analysts vs Big Data...,Mon Aug 01 21:18:32 +0000 2016,None,0,JosephTornaben
24,RT @billsoftnet: Big Data Analysts vs Big Data...,Mon Aug 01 21:18:35 +0000 2016,None,0,AleenMathews
25,#JobSearch : Senior Developer – Big Data https...,Mon Aug 01 21:18:37 +0000 2016,None,0,JetGrayJobs
26,GI JOE COBRA VINTAGE 1989 PYTHON PATROL TELE-V...,Mon Aug 01 21:18:39 +0000 2016,None,0,ultra_great
27,RT @duckduckhack: Python coders using #Conda f...,Mon Aug 01 21:18:41 +0000 2016,None,0,tavernalinux
28,#Python #statistics post on Reddit: [QUIZ] Whe...,Mon Aug 01 21:18:49 +0000 2016,None,0,fredrikpsych
29,RT @billsoftnet: Big Data Analysts vs Big Data...,Mon Aug 01 21:18:58 +0000 2016,None,0,AlexHorovitz
...,...,...,...,...,...
58,RT @Rbloggers: New R job: Big Data in Digital ...,Mon Aug 01 21:20:35 +0000 2016,None,0,SmartMedRT
59,Searching for amazing #FullStack #Developers f...,Mon Aug 01 21:20:40 +0000 2016,None,0,angavartin
60,Hot Video! John Cleese and Eric Idle of 'Monty...,Mon Aug 01 21:20:55 +0000 2016,None,0,johncnews24
61,How do I calculate the date six months from th...,Mon Aug 01 21:21:01 +0000 2016,None,0,PythonQnA
62,RT @billsoftnet: Big Data Analysts vs Big Data...,Mon Aug 01 21:21:04 +0000 2016,None,0,John__Medlock
63,Senior Developer – Big Data #Hiring Migrate Da...,Mon Aug 01 21:21:08 +0000 2016,None,0,orlandorussian
64,John Snow Labs Now Provides Curated Data in Ap...,Mon Aug 01 21:21:08 +0000 2016,None,0,treviaes
65,@matthewherper @ethanjweiss lookout for PSA da...,Mon Aug 01 21:21:20 +0000 2016,None,0,daviesbj
66,RT @wesmckinn: If you want to get more engaged...,Mon Aug 01 21:21:26 +0000 2016,None,0,sinhrks
67,John Snow Labs Now Provides Curated Data in Ap...,Mon Aug 01 21:21:38 +0000 2016,None,0,hawaiinewsupdat
68,"@arntzenius with statements, if/for etc with t...",Mon Aug 01 21:21:41 +0000 2016,None,0,ballingt
69,"RT @adamsconsulting: Past, Present and Future ...",Fri Jul 07 01:55:40 +0000 2017,None,0,marikokoloco
70,Utiliza #python con tu #Arduino: Python + Ardu...,Fri Jul 07 01:55:46 +0000 2017,None,0,Arduino_Genuino
71,RT @BLUTecnologia: ¿Qué es Big Data? ¿Qué es y...,Fri Jul 07 01:55:49 +0000 2017,None,0,CamiloALopezC
72,RT @StatsBlogs: Working With R and Big Data: U...,Fri Jul 07 01:55:50 +0000 2017,None,0,Laluito
73,Softkitect : Quantum Big Data Cloud AI Book Ch...,Fri Jul 07 01:56:00 +0000 2017,None,0,ClouDatAI
74,Softkitect : Quantum Big Data Cloud AI Book Ch...,Fri Jul 07 01:56:00 +0000 2017,None,0,ClouDatAI
75,Robert Mercer: the big data billionaire waging...,Fri Jul 07 01:56:01 +0000 2017,None,0,monstaflashlite
76,Working with #Couchbase from #Delphi - https:/...,Mon Sep 25 14:54:45 +0000 2017,None,0,mgroves
77,@michaelwaskom You mean “Before python was coo...,Mon Sep 25 14:54:48 +0000 2017,None,0,PhDemetri
78,誰一人として話題にしてないけどREPLがjava9で実装されたので\nPythonにも負けません,Mon Sep 25 14:54:48 +0000 2017,None,0,hiroakichan
79,Man Found Dead In His Bedroom Beside His Pytho...,Mon Sep 25 14:54:56 +0000 2017,None,0,marvellous997
80,RT @AriMelber: New FBI annual crime data out:\...,Mon Sep 25 14:54:58 +0000 2017,None,0,NicolasRobidoux
81,"RT @JimMarous: Potential of Fintechs, Big Data...",Mon Sep 25 14:54:59 +0000 2017,None,0,akshatprakash
82,@untipsyteacher Used for Monty Python and the ...,Mon Sep 25 14:55:01 +0000 2017,None,0,Legohelmet
83,RT @BonKu: Playgrounds as public health interv...,Mon Sep 25 14:55:01 +0000 2017,None,0,theEDpharmacist
84,Hello Python! KittenBlock V1.4 support to use ...,Mon Sep 25 14:55:02 +0000 2017,None,0,KittenBot1
85,Come and see us at poster S19 at the Big Data ...,Mon Sep 25 14:55:03 +0000 2017,None,0,IDRnews
86,@Emmanuelmarks2 @ogundamisi This python is not...,Mon Sep 25 14:55:04 +0000 2017,None,0,AAmuzie
87,Satu kali prnh ngobrol ma tmn yg gila maen onl...,Mon Sep 25 14:55:06 +0000 2017,None,0,d3_3L_3L

In [31]:
df_aux.head(1)

,text,created_at,coordinates,retweet_count,screen_name
0,RT @tonyojeda3: An Introduction to #MachineLea...,Mon Aug 01 21:16:54 +0000 2016,None,0,ErmiaBivatan

In [51]:
df_aux.text.iloc[0]

'RT @tonyojeda3: An Introduction to #MachineLearning with #Python https://t.co/TMrLLJNskx #DataScience #BigData'

In [41]:
'#MachineLearning #Python #DataScience #BigData'

'#MachineLearning #Python #DataScience #BigData'

In [50]:
def recuperar_hashtags(texto):
    '#MachineLearning #Python #DataScience #BigData'
    palavras = texto.split()
    aux = []
    for plv in palavras:
        if plv.startswith('#'):
            aux.append(plv)
    return ' '.join(aux)

In [53]:
print(recuperar_hashtags(df['text'].iloc[1]))

In [64]:
df_aux['hashtags'] = df.text.apply(recuperar_hashtags)

In [ ]:
df_aux.head()

In [68]:
df_aux.to_csv('tweets.csv', sep=';')

In [69]:
def deixar_maiusculo(texto):
    return texto.upper()

df_aux2['novo_texto'] = df_aux2.text.apply(lambda texto: texto)